-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'CARRIER_ASSIGNED';
ALTER TYPE "NotificationType" ADD VALUE 'LOAD_CANCELLED';
ALTER TYPE "NotificationType" ADD VALUE 'DOCUMENT_SCAN_QUARANTINED';
ALTER TYPE "NotificationType" ADD VALUE 'COMPLIANCE_DOCUMENT_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE 'QUOTE_EXPIRED';
ALTER TYPE "NotificationType" ADD VALUE 'INVITATION_EXPIRED';
